### ISSUE TITLE
Your old domain looks compromised

### ISSUE THREAD

**Issue by JacobJaffe** [willurmston/urmston.website-holding#6]
Hello! 

A few months ago I was checking out [Ballard Woodworks](https://ballardwoodworks.com)' site and was impressed. I saw your site linked from it-- pretty cool!

I was looking around today again through my list of websites I like, and saw that the url linked to (http://urmston.xyz/) looks ... not as you intend:
![image](https://user-images.githubusercontent.com/25315679/193705034-28ea186b-fd50-44e5-8bec-3f8a7bb8d44f.png)

I see you're using https://urmston.website/ now, so I thought I'd give you a heads up about this, in case you weren't aware of it. (Maybe you let the old domain expire when moving to the new one?) 

Anyhow, I was gonna send you an email about this, but then I saw the repo was public, so this seemed apt.

**Comment by willurmston** [comment]
Thanks @JacobJaffe, I updated it. That's my old domain. Only took a couple years 😀
